### ISSUE TITLE
">" character appears as "v"

### ISSUE THREAD

**Issue by szech** [lewish/asciiflow2#82] opened 2017-03-09 16:45 UTC
">" doesn't appear as expected.

**Comment by r0ckarong** [comment] 2017-05-02 14:25
Same for "<" and the literal "v" which is displayed as "^". Very annoying.

**Comment by mfuhrmann** [comment] 2017-07-24 13:48
"v-" appears as >

**Comment by wurzelpanzer** [comment] 2017-10-19 10:16
writing one "v" is ok, if you have multiple v's it starts to behave strange

https://i.imgur.com/3VqBEa2.png

**Comment by MikiDi** [comment] 2017-11-11 18:51
I've briefly looked into this and believe [these](https://github.com/lewish/asciiflow2/blob/master/js-lib/state.js#L162-L175) are the lines that cause this behaviour (v is a special char, when you add another v next to it you have _a special char surrounded by 1 other special char_). Should find out first what this is intended to do before breaking something else ...

**Comment by Qix-** [comment] 2019-02-11 18:12
Pretty sure this is a duplicate of #109, which was just fixed and released.

Going to optimistically close; let me know if this is still an issue for you.

**Closed by Qix-** 2019-02-11 18:12 UTC
