### ISSUE TITLE
Character v.

### ISSUE THREAD

**Issue by xhalo32** [lewish/asciiflow2#96] opened 2017-10-16 11:59 UTC
Cannot write small letter v.

**Comment by wurzelpanzer** [comment] 2017-10-19 10:15
writing one "v" is ok, if you have multiple v's it starts to behave strange

https://i.imgur.com/3VqBEa2.png

**Comment by Qix-** [comment] 2019-02-11 18:12
Pretty sure this is a duplicate of #109, which was just fixed and released.

Going to optimistically close; let me know if this is still an issue for you.

**Closed by Qix-** 2019-02-11 18:12 UTC
