### ISSUE TITLE
Allow use of unicode box drawing characters for output

### ISSUE THREAD

**Issue by tal** [lewish/asciiflow2#33] opened 2015-05-11 15:34 UTC
Have an export mode to allow unicode box drawing as well

http://en.wikipedia.org/wiki/Box-drawing_character

**Comment by rabin-io** [comment] 2016-05-17 13:40
+1

**Comment by Qix-** [comment] 2019-01-04 05:19
It's there now - go to the `?` in the top right and click "line mode" (default is "ascii mode").

**Comment by Qix-** [comment] 2020-06-15 23:11
Closing as a duplicate of #143 as there's a bit more rich information there (though I know this was created before it).

Sorry for the noise!

**Closed by Qix-** 2020-06-15 23:11 UTC
Labels: enhancement
