### ISSUE TITLE
Trying to Pay you, but its broken

### ISSUE THREAD

**Issue by timh5** [lewish/asciiflow2#151] opened 2020-06-05 15:30 UTC
This is the first time i saw the pay $3. I've been using your service for a decade.
Can you post a paypal or venmo, cuz the payment window had an error.

**Comment by vashnt707** [comment] 2020-06-05 18:21
Possibly a malware. Refer https://github.com/lewish/asciiflow2/issues/140

**Comment by Qix-** [comment] 2020-06-06 13:38
duplicate of #140. it'll get removed at some point.

**Closed by Qix-** 2020-06-06 13:38 UTC
