### ISSUE TITLE
not support encoding 'GBK'

### ISSUE THREAD

**Issue by jptiancai** [lewish/asciiflow2#61] opened 2016-05-31 09:45 UTC
![qq 20160531174415](https://cloud.githubusercontent.com/assets/1734718/15670313/5a63fe82-2757-11e6-82a8-1628efcbeef1.png)

**Comment by SteamedFish** [comment] 2017-03-21 03:31
I don't think it's related to encoding. it is related to the visual length of Chinese characters.

**Comment by Qix-** [comment] 2019-02-11 19:27
Yep, duplicate of #85.

**Closed by Qix-** 2019-02-11 19:27 UTC
Labels: duplicate
