### ISSUE TITLE
Export in lines/box mode

### ISSUE THREAD

**Issue by markand** [lewish/asciiflow2#116] opened 2018-07-27 08:34 UTC
Hello,

Would you mind allowing the export stuff in lines mode instead of ASCII when it's selected? Using [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character).

**Comment by Qix-** [comment] 2019-02-11 18:40
Duplicate of #33.

**Closed by Qix-** 2019-02-11 18:40 UTC
