### ISSUE TITLE
It seems can't support Chinese friendly

### ISSUE THREAD

**Issue by terryshenzhen** [lewish/asciiflow2#160] opened 2020-10-27 02:56 UTC
Hi brother,
when I want to type some Chinese in it , but it seems the Chinese can't display friendly because one Chinese word take 2 grids but it only display it in one grid, so that the words overlay one by one. I must type a space between every 2 words.
eg: 这是一个测试
Could you pls support Chinese?

**Comment by lewish** [comment] 2021-02-28 09:49
Duplicate of #85

**Closed by lewish** 2021-02-28 09:49 UTC
Labels: enhancement
