### ISSUE TITLE
The v letter get transformed into ^

### ISSUE THREAD

**Issue by redochka** [lewish/asciiflow2#52] opened 2016-01-06 14:10 UTC
Type v in a text box, close and open the file, the v get transformed into ^ 

hint: I noted that box containing the v letter is colored in blue..

**Comment by 4ants** [comment] 2016-09-18 13:30
Same here.
This is a bug.

**Comment by roipoussiere** [comment] 2017-03-02 11:22
Related issue : in lines mode, `v` and `-` characters are transformed into nothing.

**Comment by Qix-** [comment] 2019-02-11 18:13
Duplicate of #109, has been fixed and released now :) Go check it out!

**Closed by Qix-** 2019-02-11 18:13 UTC
