### ISSUE TITLE
lower-case V become ^ ?

### ISSUE THREAD

**Issue by icyhat** [lewish/asciiflow2#123] opened 2018-10-30 08:49 UTC
all characters are created equal?
so why lower-case v become ^ while capital V still being V?

**Comment by rawlk** [comment] 2018-11-26 17:14
Seems an earlier bug was filed: https://github.com/lewish/asciiflow2/issues/103

**Comment by Qix-** [comment] 2019-02-11 18:10
Duplicate of #109. Fixed and published already, go check it out :)

**Closed** 2019-02-11 18:13 UTC
