### ISSUE TITLE
asciiflow is spawning by popup windows

### ISSUE THREAD

**Issue by akimkelar** [lewish/asciiflow2#135] opened 2019-07-24 12:22 UTC
Once you click on the google drive icon, Asciiflow starts spawning by popups with google account authorization. It does not matter if you try to close the window or to authorize an application - it will open new and new windows every 20sec. Even while I am writing this message... Maybe that why google bans your application and nobody can authorize it.

**Comment by Qix-** [comment] 2019-07-24 13:11
Duplicate of #118. We're aware google is broken.

I cannot, however, reproduce the constant popup problem. This will get sorted out when the new version is ready.

**Closed by Qix-** 2019-07-24 13:11 UTC
