### ISSUE TITLE
Zoom is way too sensitive

### ISSUE THREAD

**Issue by frnhr** [lewish/asciiflow2#29] opened 2015-03-28 15:46 UTC
Zooming via mouse scroll is way too sensitive! It should be slowed by about factor 5 to 10. It is really hard to stop on a good zoom level because the slightest movement causes zoom to change significantly. It is really a sensitivity issue, not related to "scroll momentum" or such.

On Mac Yosemite, with Magic mouse and on trackpad, tested in Chrome and Safari.

**Comment by SkeloGH** [comment] 2016-04-01 17:22
Have same issue, a zoom reset option would be fabulous, as users like me with trackpad find impossible to reset the zoom with this degree of sensitivity and accidentally trigger it.

**Comment by frnhr** [comment] 2016-04-01 17:33
Just used ASCIIFlow yesterday again after some time. Everything was superb
except for this annoying zoom-on-scroll problem.

I'm guessing it differs from OS to OS. On Mac with the Magic Mouse it's
really problematic :(  with a classic scroll wheel it would probably be a
non-issue.

Just trying to understand how such an big annoyance survived development...


On Friday, 1 April 2016, Aaron Gonzalez <notifications@github.com> wrote:

> Have same issue, a zoom reset option would be fabulous, as users like me
> with trackpad find impossible to reset the zoom with this degree of
> sensitivity and accidentally trigger it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lewish/asciiflow2/issues/29#issuecomment-204477942>
>


-- 
LP,
Fran

**Comment by jguice** [comment] 2016-04-14 16:00
:+1:  I have to be **super** careful with the hair-trigger zoom on a mac w/ trackpad.  A checkbox to disable the scroll zoom would work too.

**Comment by Qix-** [comment] 2020-06-15 22:19
Closing as a duplicate of #28, although I realize this is a slightly different topic. AF3 will have these issues addressed entirely (and any further sensitivity bugs after release can be opened as new bugs).

**Closed by Qix-** 2020-06-15 22:19 UTC
