### ISSUE TITLE
Need diagonals

### ISSUE THREAD

**Issue by MadMonkeyMan** [lewish/asciiflow2#80] opened 2017-02-14 16:36 UTC
A nice feature would be left to right ( / ) or Right to Left ( \ ) diagonals

**Comment by Qix-** [comment] 2019-02-11 19:36
I have to think about this one but I don't see why not. My concern is how this would translate into Unicode characters.

**Comment by Qix-** [comment] 2020-06-15 22:48
Duplicate of #43. Sorry for the noise 3 years later :)

**Closed by Qix-** 2020-06-15 22:48 UTC
Labels: question

**Comment by adishavit** [comment] 2021-01-04 13:39
I would really like this feature!
I just draw this for some code comments:
```
#       /\             +----+
#      /  \            |    |
#     /    \           |    |
#    /      \          |    |
#   /        \         |    |
#  /          \        |    |
# +---+    +---+       |    |
#     |    |       +---+    +---+
#     |    |        \          /
#     |    |         \        /
#     |    |          \      /
#     |    |           \    /
#     |    |            \  /
#     +----+             \/

```
I had to add the diagonals manually. It would have been nice to do it with asciiflow.  
[Textik](https://textik.com/) has this feature, but ASCIIFLOW is way better and nicer - would be great to have this addition (even without the full blown connector facility as suggested in issue #43).
I don't see what Unicode would be an issue. Slash and Backslash are regular ASCII, no?

**Comment by Qix-** [comment] 2021-01-04 17:28
@adishavit Please keep conversation contained in the linked ticket; this is already closed as a dupe.

As for the unicode bit, it's because unicode export support is planned and thus each drawing mechanism needs an analog between ascii and unicode.

**Comment by adishavit** [comment] 2021-01-04 17:32
Sorry. Will repost in the ticket.
