### ISSUE TITLE
Pan and Zoom

### ISSUE THREAD

**Issue by bill-barron** [lewish/asciiflow2#67] opened 2016-09-01 20:52 UTC
This is a great tool. One thing I seem to use quite a bit is the zoom feature. But as I zoom in, the edges of my diagram are outside of the visible area. There doesn't appear to be any way to "pan" the viewport left, right, up or down while zoomed in. Something as simple as a scrollbar or as complex as middle-click and drag to move around my zoomed in diagram would be very very useful.

**Comment by spadfield** [comment] 2017-02-15 21:39
I just noticed that you can CTRL+drag to pan the screen. Works beautifully!

**Comment by samwalshnz** [comment] 2017-05-01 20:38
This may have something to do with using a mac, but the scrolling (zooming) seems far too sensitive and fast. Is there a way to disable to reduce the zooming speed?

**Comment by Qix-** [comment] 2019-02-11 19:27
@bill-barron I know this is ridiculously old, but could you provide a reproduction case? As far as I can tell, whatever you're referring to has since been fixed unless I'm missing something.

@spadfield on Mac it's cmd+drag - those instructions were added in #68. :)

@samwalshnz check out #111.

Closing this optimistically. Let me know if the original issue is still present!

**Closed by Qix-** 2019-02-11 19:27 UTC

**Comment by bill-barron** [comment] 2019-02-12 01:07
CTRL + Click and drag works well for me. Thanks!
