### ISSUE TITLE
Opening previously created files

### ISSUE THREAD

**Issue by clamport** [lewish/asciiflow2#102] opened 2018-01-18 18:42 UTC
I can't seem to open previously created files. If I click the drive icon and click a different file, it attempts to save the current file to the selected file. If I go to google drive and attempt to open the file, it attempts to open it as a google doc file.

How do we re-open saved flows?

**Comment by Qix-** [comment] 2019-02-11 19:13
Google drive import/export isn't working right now, I have it on my list to address it.

**Comment by Qix-** [comment] 2020-06-15 23:03
Duplicate of #118.

**Closed by Qix-** 2020-06-15 23:03 UTC
Labels: bug
