### ISSUE TITLE
Importing characters incorrectly.

### ISSUE THREAD

**Issue by stevepeak** [lewish/asciiflow2#112] opened 2018-05-20 18:48 UTC
> Thanks for a really amazing product 👍 

Found that `v` turns into `^` during importing.
https://cl.ly/2k3v0F3Y3b1x

**Comment by michkot** [comment] 2018-09-26 19:18
Confirm, happens even when writing new text (I have diacritics in the text if that might be problem)

**Comment by Qix-** [comment] 2019-02-11 18:11
Duplicate of #109. Fixed and published already, go check it out :)

**Closed by Qix-** 2019-02-11 18:11 UTC
