### ISSUE TITLE
Consider an open source license

### ISSUE THREAD

**Issue by mattdm** [lewish/asciiflow2#42] opened 2015-10-07 16:16 UTC
This is an amazing project. I'd love to see it available as open source / free software. Would you consider adding a license to it?

See GitHub's http://choosealicense.com/ site. AGPL might be a good choice, as that asks anyone running a hosted instance to contribute changes back.

**Comment by charliewolf** [comment] 2017-01-15 20:13
:thumbsup:

**Comment by Qix-** [comment] 2019-02-11 19:38
Closed by #92 and a duplicate of #31 but I'll ask @lewish if he'd be willing to use a more permissive license in the new version.

**Closed by Qix-** 2019-02-11 19:38 UTC
