### ISSUE TITLE
text is munged when using google drive

### ISSUE THREAD

**Issue by bestscarper** [lewish/asciiflow2#47] opened 2015-11-12 16:54 UTC
Specifically, letter 'v' is being turned to caret ('^') when saving/loading via google drive.

**Comment by Qix-** [comment] 2020-06-15 22:26
Duplicate of #103 (I realize this came first though the other one has more details).

Sorry for the noise 5 years later, too :)

**Closed by Qix-** 2020-06-15 22:26 UTC
