### ISSUE TITLE
Odd character replacement behavior when loading from a save

### ISSUE THREAD

**Issue by icflournoy** [lewish/asciiflow2#49] opened 2015-12-05 04:02 UTC
I have the following text/diagram and save it to Google Drive.

```
<!--Example Text--!>

   Conversation

     Receiver
```

Upon loading the saved diagram I get the following result:

```
^!++Example Text++!^

   Con^ersation

     Recei^er
```

**Comment by gaelL** [comment] 2015-12-11 23:31
I'm facing the same issue with the import from raw text input. (Not only from google drive).

**Comment by gaelL** [comment] 2015-12-11 23:49
To give a workaround and hope it will help you to fixe : 

Simply use `text tool` to import raw text. With `text tool`, we have not the side effect as we have with `import-button`.

**Comment by Qix-** [comment] 2020-06-15 22:28
Closing as a duplicate of #103 (I know this came first, but that issue has more information about it).

Also, sorry for the noise 5 years later :)

**Closed by Qix-** 2020-06-15 22:28 UTC
