### ISSUE TITLE
Keyboard shortcuts to commands

### ISSUE THREAD

**Issue by keke8273** [lewish/asciiflow2#81] opened 2017-02-23 22:47 UTC
Is there a list of shortcut for commands? 

It would be nice to have keyboard shortcut to commands, such as draw, resize, etc.

**Comment by oldmud0** [comment] 2017-07-18 21:33
Bump.

**Comment by Qix-** [comment] 2019-02-11 19:19
Duplicate of #90.

**Closed by Qix-** 2019-02-11 19:19 UTC
