### ISSUE TITLE
Each Chinese character should occupy two ASCII characters to display.

### ISSUE THREAD

**Issue by lar-ry** [lewish/asciiflow2#152] opened 2020-06-10 09:16 UTC
Each Chinese character should occupy two ASCII characters to display, 
otherwise it will display abnormal.

每个中文字符应该占两个ASCII字符显示，否则将会显示异常。
```
+----------------------------------------+
|                                        |
|  每个中文字符应该占两个ASCII字符显示，否则将会显示异常。        |
|                                        |
|  Each Chinese character should occupy  |
|  two ASCII characters to display,      |
|  otherwise it will display abnormal.   |
|                                        |
+----------------------------------------+
```

**Comment by Qix-** [comment] 2020-06-15 23:14
Duplicate of #85.

**Closed by Qix-** 2020-06-15 23:14 UTC
