### ISSUE TITLE
Infinite pop-up windows when Google Drive Saving

### ISSUE THREAD

**Issue by alexandreMartinEcl** [lewish/asciiflow2#155] opened 2020-07-07 14:01 UTC
When willing to use Google Drive saving option, Google Auth pop up started to appear, infinitely and at a space of 1 every 2 seconds.

I had to remove the website from the authorised ones for pop ups.

Mozilla firefox, Linux Mint (if it matters)

![image](https://user-images.githubusercontent.com/32698524/86792788-1be13880-c06b-11ea-93d0-c33a2f085595.png)

![image](https://user-images.githubusercontent.com/32698524/86792475-d1f85280-c06a-11ea-8734-2be3ca28c3ca.png)

**Comment by crazybber** [comment] 2020-07-07 14:48
github may be a more better choice ,

**Comment by Qix-** [comment] 2020-07-08 19:27
Yep, this is a well-known issue.

Duplicate of #118

**Closed by Qix-** 2020-07-08 19:27 UTC
