### ISSUE TITLE
Error when tried to login using my google account

### ISSUE THREAD

**Issue by soyeliel** [lewish/asciiflow2#139] opened 2019-10-07 13:25 UTC
Hello guys, 

Just to let you know that I receive an error every time I try to login using my google account.
"Sign in with google temporarily disabled for this app"

I google it and seems it is related with this document:
https://support.google.com/cloud/answer/7454865?hl=en

**Comment by Qix-** [comment] 2019-10-07 16:15
Duplicate of #138 
Duplicate of #136 
Duplicate of #135 
Duplicate of #118 
Duplicate of #102 

We're well aware of the issue. 🙃

**Closed by Qix-** 2019-10-07 16:15 UTC
