### ISSUE TITLE
Google Sign In is Broken

### ISSUE THREAD

**Issue by chadsaun** [lewish/asciiflow2#153] opened 2020-06-11 22:10 UTC
Just tried to sign in with my Google Account and got this error below:

```
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.
```

![Screen Shot 2020-06-11 at 4 08 21 PM](https://user-images.githubusercontent.com/381024/84443971-eb3de880-abfd-11ea-8717-fa6e177fbc1e.png)

**Comment by Qix-** [comment] 2020-06-15 22:12
Duplicate of #118.

**Closed by Qix-** 2020-06-15 22:12 UTC
