### ISSUE TITLE
V becomes ^ when v is directly above another v

### ISSUE THREAD

**Issue by client4** [lewish/asciiflow2#103] opened 2018-01-29 00:43 UTC
In text mode, a "v" is turned into "^".

**Comment by whj2819** [comment] 2018-04-21 14:33
me too

**Comment by rawlk** [comment] 2018-11-26 17:16
Seems to also be filed in https://github.com/lewish/asciiflow2/issues/96 , #82, #52

**Comment by Qix-** [comment] 2019-02-11 18:10
Duplicate of #109. Fixed and published already, go check it out :)

**Comment by eeliu** [comment] 2019-03-27 10:39
###  Does it fix ?

![图片](https://user-images.githubusercontent.com/27064129/55069647-7ac1af00-50bf-11e9-889b-9d8a42f1cceb.png)

**Comment by Qix-** [comment] 2019-03-27 12:27
Neat, good catch @eeliu.

**Comment by mort3za** [comment] 2019-06-14 07:39
I think it's better to use these unicode characters for arrow shapes:
```
˄ ˅
&#x2C4; and &#x2C5; respectively.
```

**Comment by lewish** [comment] 2021-02-28 09:47
Pretty sure this is fixed now.

**Closed by lewish** 2021-02-28 09:47 UTC
Labels: bug
